name: Compilar a EXE
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Crear Ejecutable
      run: |
        python -m PyInstaller --noconsole --onefile --name="Actualizacion_Sistema" main.py

    - name: Subir Archivo Final
      uses: actions/upload-artifact@v4
      with:
        name: FundilloWindowsEXE
        path: dist/Actualizacion_Sistema.exe
