name: Compilar a ZIP
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Crear ZIP
      run: |
        mkdir dist
        Compress-Archive -Path . -DestinationPath dist/Actualizacion_Sistema.zip

    - name: Subir Archivo Final
      uses: actions/upload-artifact@v4
      with:
        name: FundilloWindowsZIP
        path: dist/Actualizacion_Sistema.zip
